import { Link } from "react-router-dom";
import { useEffect, useState } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
} from "recharts";
import {
  PieChart,
  Pie,
  Cell,
  Tooltip,
  Legend,
  ResponsiveContainer,
} from "recharts";

function ReportsPage() {
  const user = JSON.parse(
  localStorage.getItem("user") || "{}"
);

const [transactions, setTransactions] = useState([]);

const fetchTransactions = async () => {
  try {
    const response = await fetch(
      `http://localhost:5000/api/transactions/user/${user.id}`
    );

    const data = await response.json();

    if (data.success) {
      setTransactions(data.transactions);
    }
  } catch (error) {
    console.log(error);
  }
};

useEffect(() => {
  fetchTransactions();
}, []);

const income = transactions
  .filter((t: any) => t.type === "Income")
  .reduce(
    (sum: number, t: any) => sum + t.amount,
    0
  );

const expense = transactions
  .filter((t: any) => t.type === "Expense")
  .reduce(
    (sum: number, t: any) => sum + t.amount,
    0
  );
  const monthlyData = Array.from({ length: 12 }, (_, index) => ({
  month: new Date(0, index).toLocaleString("default", {
    month: "short",
  }),
  expense: 0,
}));
transactions.forEach((t: any) => {
  if (t.type === "Expense") {
    const monthIndex = new Date(
      t.createdAt
    ).getMonth();

    monthlyData[monthIndex].expense +=
      t.amount;
  }
});
  const categoryMap: any = {};

transactions.forEach((t: any) => {
  if (t.type === "Expense") {
    categoryMap[t.category] =
      (categoryMap[t.category] || 0) + t.amount;
  }
});

const categoryData = Object.keys(categoryMap).map(
  (key) => ({
    name: key,
    value: categoryMap[key],
  })
);
const topCategory =
  categoryData.length > 0
    ? categoryData.reduce((prev, current) =>
        prev.value > current.value
          ? prev
          : current
      )
    : null;
const incomeExpenseData = [
  { name: "Income", value: income },
  { name: "Expense", value: expense },
];

  const COLORS = ["#22c55e", "#ef4444"];

const exportPDF = () => {
  const doc = new jsPDF();
  const storedUser = localStorage.getItem("user");

const user = storedUser
  ? JSON.parse(storedUser)
  : { name: "Unknown", email: "Unknown" };

doc.setFontSize(20);
doc.text("FinTrack - Personal Finance Report", 14, 20);

doc.setFontSize(12);

doc.text(`Name : ${user.name}`, 14, 35);
doc.text(`Email : ${user.email}`, 14, 45);
doc.text(`Generated On : ${new Date().toLocaleDateString()}`, 14, 55);

// Extra space after Generated On
doc.text(`Total Income : Rs. ${income}`, 14, 75);
doc.text(`Total Expense : Rs. ${expense}`, 14, 85);
doc.text(`Net Balance : Rs. ${income - expense}`, 14, 95);



autoTable(doc, {
  startY: 115,
  head: [["Title", "Amount", "Type", "Category"]],
  body: transactions.map((t:any) => [
    t.title,
    t.amount,
    t.type,
    t.category,
  ]),
});
const pageHeight = doc.internal.pageSize.height;

doc.setFontSize(10);
doc.text(
  "Generated by FinTrack Expense Management System",
  14,
  pageHeight - 10
);

doc.save("finance-report.pdf");
};
  return (
    <div className="p-8">
      <div className="flex justify-between items-center mb-8">
        <h1 className="text-4xl font-bold">
          Reports & Analytics
        </h1>

        <Link
          to="/dashboard"
          className="bg-blue-600 text-white px-4 py-2 rounded"
        >
          Back to Dashboard
        </Link>
        <button
  onClick={exportPDF}
  className="bg-red-600 text-white px-4 py-2 rounded"
>
  Export PDF
</button>
      </div>
<div className="bg-yellow-100 p-5 rounded shadow mb-6">
  <h2 className="text-xl font-semibold mb-2">
    💡 Spending Insight
  </h2>

  <p>
    Highest Expense Category:
    <strong>
      {" "}
      {topCategory?.name || "N/A"}
    </strong>
  </p>

  <p>
    Amount:
    <strong>
      {" "}
      ₹{topCategory?.value || 0}
    </strong>
  </p>
</div>
      <div className="grid grid-cols-3 gap-4 mb-8">
        <div className="bg-green-100 p-4 rounded shadow">
          <h3>Total Income</h3>
          <p className="text-3xl font-bold text-green-600">
            ₹{income}
          </p>
        </div>

        <div className="bg-red-100 p-4 rounded shadow">
          <h3>Total Expense</h3>
          <p className="text-3xl font-bold text-red-600">
            ₹{expense}
          </p>
        </div>

        <div className="bg-blue-100 p-4 rounded shadow">
          <h3>Balance</h3>
          <p className="text-3xl font-bold text-blue-600">
            ₹{income - expense}
          </p>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-8">
        <div className="bg-white p-6 rounded shadow">
          <h2 className="text-xl font-semibold mb-4">
            Income vs Expense
          </h2>

          <ResponsiveContainer width="100%" height={300}>
            <PieChart>
              <Pie
                data={incomeExpenseData}
                dataKey="value"
                outerRadius={100}
                label
              >
                {incomeExpenseData.map((_, index) => (
                  <Cell
                    key={index}
                    fill={COLORS[index]}
                  />
                ))}
              </Pie>

              <Tooltip />
              <Legend />
            </PieChart>
          </ResponsiveContainer>
        </div>

        <div className="bg-white p-6 rounded shadow">
          <h2 className="text-xl font-semibold mb-4">
            Category Breakdown
          </h2>

          <ResponsiveContainer width="100%" height={300}>
            <PieChart>
              <Pie
                data={categoryData}
                dataKey="value"
                outerRadius={100}
                label
              >
                <Cell fill="#3b82f6" />
                <Cell fill="#f59e0b" />
              </Pie>

              <Tooltip />
              <Legend />
            </PieChart>
          </ResponsiveContainer>
        </div>
      </div>
      <div className="bg-white p-6 rounded shadow mt-8">
  <h2 className="text-xl font-semibold mb-4">
    Monthly Expense Trend
  </h2>

  <ResponsiveContainer width="100%" height={300}>
    <BarChart data={monthlyData}>
      <CartesianGrid strokeDasharray="3 3" />
      <XAxis dataKey="month" />
      <YAxis />
      <Tooltip />
      <Bar dataKey="expense" fill="#ef4444" />
    </BarChart>
  </ResponsiveContainer>
</div>
    </div>
  );
}

export default ReportsPage;